### ISSUE TITLE
how the samples run

### ISSUE THREAD

**Issue by invegat** [PacktPublishing/React-and-React-Native#7]
Explaining that React automatically looks up the directory tree for a node_modules folder that contains the matching "import"s  in main.js would eliminate some confusion.

**Comment by adamboduch** [comment]
Hi @invegat,

If you take a look at the [README](https://github.com/PacktPublishing/React-and-React-Native/blob/master/README.md), you'll find specific instructions for running the examples.

Webpack is the bundler that finds modules from `node_modules` based on `import` statements.

For example, if I want to import one of my own modules, I would do so relative to the current module:
```js
import * from './my-module';
```

The Webpack loader knows that I want something from `node_modules` because I just specify the name of the module, instead of a path:
```js
import * from 'react';
```

Let me know if this helps.
